name: Strong VPN Server (WireGuard)

on:
  workflow_dispatch:   # تشغيل يدوي

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Install WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard qrencode curl

          # توليد مفاتيح
          wg genkey | tee server_private.key | wg pubkey > server_public.key
          wg genkey | tee client_private.key | wg pubkey > client_public.key

          SERVER_PRIV=$(cat server_private.key)
          SERVER_PUB=$(cat server_public.key)
          CLIENT_PRIV=$(cat client_private.key)
          CLIENT_PUB=$(cat client_public.key)

          # إعداد السيرفر
          cat > wg0.conf <<EOF
          [Interface]
          Address = 10.20.0.1/24
          ListenPort = 51820
          PrivateKey = $SERVER_PRIV

          [Peer]
          PublicKey = $CLIENT_PUB
          AllowedIPs = 10.20.0.2/32
          EOF

          sudo mkdir -p /etc/wireguard
          sudo mv wg0.conf /etc/wireguard/wg0.conf
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0

          # إعداد ملف العميل
          cat > client.conf <<EOF
          [Interface]
          PrivateKey = $CLIENT_PRIV
          Address = 10.20.0.2/24
          DNS = 1.1.1.1

          [Peer]
          PublicKey = $SERVER_PUB
          Endpoint = $(curl -s ifconfig.me):51820
          AllowedIPs = 0.0.0.0/0, ::/0
          PersistentKeepalive = 25
          EOF

          echo "================ Client Config ================="
          cat client.conf
          echo "================================================"

          echo "✅ امسح هذا الكود QR في تطبيق WireGuard:"
          qrencode -t ansiutf8 < client.conf

      - name: Keep server alive
        run: |
          echo "Keeping server alive for 6 hours..."
          sleep 21600   # 6 ساعات
